# Generated by Django 2.1.7 on 2019-05-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddr',
            name='visitCount',
            field=models.IntegerField(default=0),
        ),
    ]
