# Generated by Django 2.1.7 on 2019-05-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ipaddr_visitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddr',
            name='visitTime',
            field=models.CharField(default='2019/5/8 15:41', max_length=50),
        ),
    ]
